#!/bin/bash

# Replace the following URL with a public GitHub repo URL
https://github.com/spenikhk/Elephant-Project/blob/master/README.md
webappname=mywebapp$AutomationforthePeople

# Create a resource group.
az group create --location eastus2--name ElephantProject

# Create an App Service plan in `FREE` tier.
az appservice plan create --name $ElephantProject123 --resource-group ElephantProject --sku FREE

# Create a web app.
az webapp create --name $ElephantProject123 --resource-group ElephantProject --plan $ElephantProject123
# Deploy code from a public GitHub repository. 
az webapp deployment source config --name $ElephantProject123 --resource-group ElephantProject \
--repo-url $https://github.com/spenikhk/Elephant-Project/blob/master/README.md --branch master --manual-integration

# Copy the result of the following command into a browser to see the web app.
echo http://$webappname.azurewebsites.net
